language: node_js
script:
  - echo $SQS_MESSAGE
  - echo $SOME_VARIABLE
  - echo $HOME
before_install:
  - this-will-fail
install:
  - this-will-fail-too
env:
  global:
    - secure: GG57yLaZw6xXtr1eNNGsKMseadOFsr/OXNQ6ioMKJAqooYHZ7CahhSLpNgxFbav6/+xb79LV183F0G8K9fPX9rf04dvY9InMTTEp5uV5yB3Sn6iR0ZOTmZCwyS2+KChqHDNT6mTwsUiat7ahUqPnR5gcV0cn0qvc9D1TynHfgggDa9WMtvZ6MYj2Up4P/+OwDbGVr957bi8Ykd+Jim2LUiSzaDr00ZnKO9V3BKOLHe6ey7yGtQGjLGJ62jKyyPajOKgEUN4oGkQbL+/wp4bRh2XFRTVXByG0nUj3v0PdtxuwibkkzyGQ+Z2+OaVFpPzSsQ/4kCUrb628ESwNDelMJw==
    - secure: lOl7WQ8v0UrZDM85XvZrg8MoQ2uhGhLyTD4oeUPE/BZjr+seam1tWJuzr9qtJPeTdSAlYolIc6CeaIGuajyGpzB2ysssHxfQ4d2WLLxyRcnmrIZhZYuD6golFfT5QGZ3KtxM9I75dEk/WQlEXpv0TGOh96FtLB3XTsT8rpl9y6vOSYPimbfU1Oak0Guy9UL3FXNSCpCE/8trNnD9V2/Ebb/RO0raxz8cL9tDcF4D4SVPQ80Utp4e1fEqM5nXlnsmPIVAXCxi8kO9avBEYa5NL870cz0QmLros/PwJEEOzMIKrFAhdEhwjIpZCz0wj4bu8f880+nyt/g23V3CoxOQwQ==
    - secure: SmrKN50KqFOIKRK8WanLBfhRdNogipGpnV36NkDNEBt6Q2rHw4GlvvWHBAWRdBpnP/oHIkOL6e1MH62SQzDdPg0PDo84doMwhPPFkX0AgZE1sbvMNIuE6PHYctTkY6BH9TJV0f18dsDf9PRgKWWdgdw8e9I1N+C7fH3f7B/IfEqxR5NQE7eYBmtVgy0KGYWeNmjjsgGiSC91+ToKCZ4kpykYqYdTgNS62y1JpM+5Y8KsA+k6h6BsPsPLCw/SHGo1jGqayKDMQRLSEUGaZf6/Fd8bS2LXHKJgdDI/nSpvxMSGaE53xGqgU2DMyGQJjYEEjnTKqfE2aRyHcE0TYem1Mg==
    - secure: Fj1pOtYsnqvV/DEiGvY8QvMCshV05mL7v+yJHXwUgxS107FBAnN+skzBBAhSZax/GZOjlSAekPzacPxU/rn1eAMRvEwmgRZdJL/stMgFU8y4bfj6rH/REwongoqoI/IIHUXkdIklqVEX3rt69rEpquq7MQ4Fa/jRM4El2hZ+Jt+fPNkWDfrPtAh+ngXUM6BjhvYW7DPVe1HBb4ZoIkWn07iNOJ94hiROC8Hdzk/al5EadtGIyQjuV1fjTrtm27tZKfwwVb3kbnFQsDTHxRjmmFTgCSgUhcUeUQ8JdfMfJr59TTpKpE2Ju2yTOdQ9TOO4Y9Ab4WEqlg40+x+MaXrhQw==
    - secure: j7Iw1lMBsJcw3bZRUZw2PD98OFsoQNwCj8lR7Hy2vZrJ0EVYKTJ9pLI2sAG/g4Q9OFFYKnrYAwUClgfSisCnMvcnKu5+uxHVblNw45YhyyiczKXIcydQ2b3JYter95gn7O1wnKDB6xdZ78MgqSopwPqZKtAr8GDZ4/cRiNlWFqX5LLnhdf6use7DXsunP6IFMXOOmSVT5uXTMpWeayjGb3+qZYpvDjgIr0bmtT2ZeiNt8b+rBMnAhkWWTWgOtYvgDoxRgEg2Pd5SpT5BNKtJiMhjSLLrthz5ec1zqDp5CfMRQ/NyZq5FTPZT6O18r4xalEk+YuwYNHopHHdVys46uQ==
