language: node_js
script:
  - echo $SQS_MESSAGE
  - echo $SOME_VARIABLE
  - echo $HOME
install:
  - this-will-fail-too
env:
  global:
    - secure: qs4yi8VOhkQ9MO1ppcRwB+09l2IusholW8pXamib1sgNiGeKkb3FdOyW87+ihe7nxiwOZ6vVx9imb9HckdcRx+XYd938qKO4ci1IrCxxH0ko893ZiM/WskEGdWgiXXX1xK+hpjy8HWaGQ8c/+A9AgvUJALY2fQEYOapU1k1FMQceYVd7oZLYWPYVZ/Mh+KJqDlya9W9rnxkjDZYOr27iCldDZw/4+KQ6h4PCK8vft+9Mptn1Rt/1oYjtpxuhTj/XJ6zOIMzBig9LAPvezIXT/cmkzZ4CvXhZxMhBCtW0CYAZR9udekri0TCJCq/8K9HRACdVZ1Ssj9a55b7sUiqX7w==
